run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - goimports
    - misspell
    - gofmt
    - unparam
    - unconvert
    - whitespace
    - godot

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/rinat074/chat-go
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  funlen:
    lines: 100
    statements: 50
  godot:
    period: true
    capital: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
    - text: "should have a package comment"
      linters:
        - revive
    - text: "exported .* should have comment"
      linters:
        - revive

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 