version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/chatapp
      - GRPC_SERVER_ADDRESS=:50051
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
    restart: unless-stopped

  chat-service:
    build:
      context: .
      dockerfile: services/chat-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/chatapp
      - REDIS_URL=redis:6379
      - GRPC_SERVER_ADDRESS=:50052
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  gateway-service:
    build:
      context: .
      dockerfile: services/gateway-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HTTP_SERVER_ADDRESS=:8080
      - AUTH_SERVICE_ADDRESS=auth-service:50051
      - CHAT_SERVICE_ADDRESS=chat-service:50052
      - REDIS_URL=redis:6379
    depends_on:
      - auth-service
      - chat-service
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data: 